# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4fd3e64ebb956a9a1a460592ae6d2023cfb9be5dceeecf4f5ae5c1d5098e201c8fc36699fe1e35dc6e2e80735a7667ebdf484c616b6162c99b833343b5dc55d

test:
  secret_key_base: 1f57de1c8319935b0f005b01ee7cf1ed2b51d671aa145f71a714cb7e6a8fe7b10fa740707bcfa972ef514dbda98d5f0fa497838b81ef0c93bddb8db2b1cab292

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
